name: main

on:
  push:
    branches: [ main ]

jobs:
  workflow_run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7.9'

    - name: Setup Environment
      run: |
        python3 -m pip install --upgrade pip setuptools wheel
        python3 -m pip install -r requirements.txt
        wget -q https://raw.githubusercontent.com/dapr/cli/master/install/install.sh -O - | /bin/bash
        echo "/home/runner/.dapr/bin" >> $GITHUB_PATH

    - name: Setting up dapr
      id: create_components
      run: |
        python3 export_secrets_to_components.py
        dapr init
        dapr run --app-id dapr_sidecar -d components -P grpc -G 20000 &
      env:
        COMPONENT_LOCALREDISSTATE: ${{ secrets.COMPONENT_LOCALREDISSTATE }}
        COMPONENT_LOCALKAFKA: ${{ secrets.COMPONENT_LOCALKAFKA }}

    - name: Step 1 - Retrieve state
      id: step_1
      run: python3 step_1.py

    - name: Step 2 - Push a value
      id: step_2
      run: python3 step_2.py

    - name: Step 2 - Push and pull a value
      id: step_2
      run: dapr run --app-id step_4 --app-protocol grpc --app-port 50051 -d ./components python3 step_3.py